### ISSUE TITLE
Frames generated at slice edges

### ISSUE THREAD

**Issue by mivermeu** [stcorp/procsim#42]
A long continuous data take may be split into multiple slices, the middle slices of which will be of nominal length. Slices are generated with some overlap. In general, splitting adjacent slices into frames should be done in such a way that the former slice boundaries are invisible. That is to say, frames nominally only overlap as much as the configured frame overlap interval present at the end of each frame.

However, in https://github.com/stcorp/procsim/issues/35#issuecomment-1141096402 a situation is described in which the theoretical end of a slice (including overlap) is equal to the sensing stop time. It is then expected that the sensing stop of the final generated virtual frame is equal to the sensing stop of the data take, even though this takes the frame beyond its regular overlap well into the next slice: it becomes a merged frame under normal conditions. Had there been another slice following this one, the overlap between frames on the slice boundary would be noticeably larger. In some cases there could be entire redundant frames.

How do we determine whether to generate frames right up to the sensing times if we only have knowledge of a single slice?

**Comment by lmar76** [comment]
Consider the following figure (figure 4 of the BIOMASS Production Model v3.4):
![slice_frame_grids](https://user-images.githubusercontent.com/20207042/173042348-dddc1427-f6af-4e68-933a-76653e20562e.png)

For each slice in the figure there are up to 5 frames which are located between the vertical dashed lines corresponding to the slice grid "tie points", i.e. the slice grid intervals without the overlaps.

Consider the slice 2 (which is the same scenario tested in #35). In this case, since the data take starts after the slice 2 theoretical start, you have a partial slice. Procsim could understand this by comparing the calculated slice times with the `TOI/Start` value in the job order (if `begin_end_position_from_toi` is set to `true` in the configuration) or from `begin_position` or from the MPH of input Sx_RAW__0S (`om:phenomenonTime/gml:TimePeriod/gml:beginPosition`).
The frames corresponding to slice 2 are frame 7 to frame 10 (frame 6 and 7 are merged), so up to the last frame before the vertical line). This means that the slice's final overlap is not covered (and it was also my mistake during the evaluation of the times in #35).

Consider the slice 3. In this case you have a complete slice. Also in this case Procsim could compare the calculated slice times with the TOI start/stop in the job order or from begin/end positions in the configuration or from the MPH. Now, the frames corresponding to slice 3 are frame 11 to frame 15.

The most "tricky" case is the slice. In this case the data take ends after the vertical line but the slice 9 is too short and it is merged with the previous one. In this case also the partial frame 41 is generated.

To summarize, There are 3 cases:
- partial slice:
   - data take starts after the slice theoretical start (i.e. first slice in the data take): in this case the time boundary is [sensing start, slice grid stop + frame margin] (e.g. frame 10 in the figure goes 2 seconds after the vertical line)
   - data take ends before the theoretical slice stop (i.e. last slice in the data take): in this case the time boundary is slice grid start, sensing stop].
- complete slice: the time boundary is [slice grid start, slice grid stop + frame margin] (e.g. frame 15 in the figure goes 2 seconds after the vertical line)
- merged slice:
   - data take starts _before_ the slice theoretical start (i.e. first slice in the data take merged to the second one): in this case the time boundary is [sensing start, slice grid stop + frame margin]
   - data take ends _after_ the theoretical slice stop (i.e. last slice in the data take merged with the previous one, see slice 8 in figure): in this case the time boundary is slice grid start, sensing stop].

How to distinguish the 3 cases:
- from job order's TOI start stop: during the generation of the virtual frame product, TOI start/stop times are equal to the input Sx_RAW__0S sensing start/stop times. Comparing these times with the calculate (theoretical) times it should be possible to determine if the input slice is partial, complete or merged.
- from `begin_position`/`end_position`: same as TOI.
- from the MPH of the input Sx_RAW__0S: sensing time can be extracted from `om:phenomenonTime/gml:TimePeriod/(gml:beginPosition|gml:endPosition)`

**Comment by lmar76** [comment]
It works as expected! Thank you!
