### ISSUE TITLE
tag and/or release for biomass L1

### ISSUE THREAD

**Issue by melchisedek** [stcorp/procsim#51]
Hi, 

can you please create a tag or release from master branch commit 7ef3893d2ae54cf9c02ed13f8e0a2da4f063653c?

this would help to better handle the different development stages (support L0, L1, L2a).

thank you very much

**Comment by pe1obw** [comment]
Hello melchisedek, 

Could you explain who you are, and what and why exactly should be done? 

In general, if a new feature, or set of features is added, such as support for a range of products, a new release is made.
For every release we create a new branch, to allow for bugfixes on that specific release. Then, the CHANGELOG is updated, a smoke test is done and a tag is placed.

It was not planned to use tags, other as for these releases!

**Comment by melchisedek** [comment]
Shure the reason is that 

the actual developing of pocsim 'features' are only merged into the master branch without tagging or releases.

Since v1.7.0 - 2022/05/23
add a number of enhancements and patches
- add support for the Framer
- add support for additional product types
- ...
You should know better what you are doing ;)

But these changes have disruptive effects (incompatible scenario configurations / other mandatory metadata). It was helpful to have tag/release before you merge the changes.

It is a mess to keep the procsim runnable.

- L0 Processing runs with release 1.7.0 but not with master
- L1 Processing runs with master:HEAD~3 but not with master
- L2 Processing runs with master

**Comment by pe1obw** [comment]
Hi melchisedek,

Not sure if we understand all your issues, but we realize that, especially due to the implementation of new specifications, incompatibilities occur. Therefore, we made two new releases:

- version 1.8.0 contains several fixes for the frames and better support for data takes. It implements BIO-ESA-EOPG-EEGS-TN-0051 2.3.
- version 1.9.0 is the same, but with support for the 'new' L2a types.

Hope this helps! Comments invited.

**Comment by melchisedek** [comment]
Yes, thank you very much.

that is exactly what we need. 

have a nice weekend
